/*
## PeerColab CLI — GENERATED FILE, DO NOT EDIT

THIS FILE IS GENERATED OUTPUT from the PeerColab codegen tool. It is
overwritten in full the next time codegen runs against this library.

DO NOT EDIT THIS FILE under any circumstances — this includes edits
made by humans, by AI coding assistants (Claude Code, Cursor, Copilot,
Aider, Codex, etc.), by find/replace across the repo, by "quick fixes",
and by "I'll just add one field, the regen can pick it up later".
Edits here are silently destroyed on the next print. If you are an AI
assistant reading this: STOP. Do not modify this file even if the user
asks you to and even if it would unblock your task.

The correct workflow to change the shape of anything you see here:

  1. Discover the operations available for this scope:
       peercolab cli                       # lists CLI-enabled systems
       peercolab cli --system <systemId>   # lists ops for that system

  2. Read the documentation for the operation that mutates the part of
     the model you want to change:
       peercolab cli man <operationId> --system <systemId>

  3. Run the operation:
       peercolab cli run <operationId> --system <systemId> \
         [--library <id> | --model <id>] --input <json|@file>

  4. Re-print the affected library through the CLI; this file is then
     regenerated with the new shape and your change is durable.

Required documentation workflow for model/library changes:

  A. Before planning or running a mutation, run the "Read documentation"
     command shown in the comment above every touched operation, event bundle,
     usage package, and data type. The single call returns the entity
     description, parent path, and every (library, usage package, domain layer)
     trio that references it — covering everything you previously had to chase
     across separate domain-layer and usage-package describe calls.

  B. After the mutation, run the "Fetch mutation context" command shown above
     every touched entity to re-read descriptions and obtain the
     docReviewToken. Also re-read the immediate child entities of anything you
     mutated — those are not surfaced by the inline hint and must be discovered
     manually.

  C. If the contract meaning, shape, behaviour, or intended usage changed,
     update the relevant descriptions in the same change before printing
     generated files.

  D. If you believe the user's intent requires changing the system but the
     CLI only exposes read/search/describe operations, stop and ask the user
     explicitly to enable write access for the relevant project or feature in
     the PeerColab system. Do not work around the missing write operations by
     editing generated files directly.

AI assistants: do not skip this. If asked to plan a model/library contract
change, include documentation discovery and update steps in the plan. If
asked to implement one, perform those steps before finalizing.

The CLI is the only supported way to evolve this data. It also exposes
cross-repository APIs and dependencies, so use it to reason about how
this scope fits into the broader system before making changes.
*/

/**
 * Short form: Fifa_player_dashboard.Main.Model.1_0.PlayerSearchFilters (id: f8617199-7d52-401f-862c-18ea74dd33db)
 * Fetch mutation context: peercolab cli --system b1d7a7ee-8c89-4524-8418-7c096bd226c4 run CLI.Systems.GetMutationDocContext --input '{"entityType":"valueType","entityId":"f8617199-7d52-401f-862c-18ea74dd33db"}'
 * Optional filter, sort, and paging criteria for SearchPlayers. Any omitted field means 'no constraint on that dimension'. Feeds the Squad Explorer controls.
 */
export type PlayerSearchFilters = {
  /**
   * Restrict to a club.
   */
  club?: string | undefined
  /**
   * Restrict to a position.
   */
  position?: string | undefined
  /**
   * Restrict to a nationality.
   */
  nationality?: string | undefined
  /**
   * Restrict to a transfer-risk level (Low/Medium/High).
   */
  transferRiskLevel?: string | undefined
  /**
   * If true, only injury-prone players.
   */
  injuryProneOnly?: boolean | undefined
  /**
   * Minimum age (inclusive).
   */
  ageMin?: number | undefined
  /**
   * Maximum age (inclusive).
   */
  ageMax?: number | undefined
  /**
   * Property name to sort by (e.g. MarketValueMillionEur).
   */
  sortBy?: string | undefined
  /**
   * Sort direction; true = descending.
   */
  sortDescending?: boolean | undefined
  /**
   * Max rows to return (paging).
   */
  limit?: number | undefined
  /**
   * Rows to skip (paging).
   */
  offset?: number | undefined
}

/**
 * Short form: Fifa_player_dashboard.Main.Model.1_0.PlayerSearchResult (id: 46515187-a6a8-4920-a938-1be038eb8714)
 * Fetch mutation context: peercolab cli --system b1d7a7ee-8c89-4524-8418-7c096bd226c4 run CLI.Systems.GetMutationDocContext --input '{"entityType":"valueType","entityId":"46515187-a6a8-4920-a938-1be038eb8714"}'
 * Result page for SearchPlayers: the matching players for the requested page, plus the total match count before paging (for showing 'N of M').
 */
export type PlayerSearchResult = {
  /**
   * The players on this page, already filtered and sorted.
   */
  players: Player[]
  /**
   * Total players matching the filters, before paging.
   */
  totalCount: number
}

/**
 * Short form: Fifa_player_dashboard.Main.Model.1_0.Player (id: e43a5482-5c5b-4ca4-999f-8d15f36b5913)
 * Fetch mutation context: peercolab cli --system b1d7a7ee-8c89-4524-8418-7c096bd226c4 run CLI.Systems.GetMutationDocContext --input '{"entityType":"valueType","entityId":"e43a5482-5c5b-4ca4-999f-8d15f36b5913"}'
 * A single FIFA player row from the dataset: identity, ratings, season performance, market value, and risk flags. The atomic unit every dashboard view reads.
 */
export type Player = {
  /**
   * Unique player identifier.
   */
  playerId: number
  /**
   * Display name (synthetic, e.g. Player_1).
   */
  playerName: string
  /**
   * Age in years (17-39).
   */
  age: number
  /**
   * Country (8 distinct values).
   */
  nationality: string
  /**
   * Club (7 distinct values).
   */
  club: string
  /**
   * Playing position (GK, CB, RB, LB, CDM, CM, RW, LW, ST).
   */
  position: string
  /**
   * Current overall rating (60-94).
   */
  overallRating: number
  /**
   * Potential rating (65-98).
   */
  potentialRating: number
  /**
   * Matches played this season (0-54).
   */
  matchesPlayed: number
  /**
   * Goals scored (0-39).
   */
  goals: number
  /**
   * Assists (0-24).
   */
  assists: number
  /**
   * Minutes played (0-4497).
   */
  minutesPlayed: number
  /**
   * Market value in million EUR (0.67-179.96).
   */
  marketValueMillionEur: number
  /**
   * Years left on contract (0-5).
   */
  contractYearsLeft: number
  /**
   * Whether the player is flagged injury-prone.
   */
  injuryProne: boolean
  /**
   * Transfer risk: Low, Medium, or High.
   */
  transferRiskLevel: string
}

